# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuandao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='article_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
